---
environment:
  ALWAYS_APPLIED_KEY: "envvar to be set regardless of which model is active"

models:
  OpenAI: &active
    environment:
      OPENAI_API_KEY: "" # Required
    provider: ChatOpenAI
    args:
      model: claude-opus-4-6
      configuration:
        baseURL: "https://maas-rhdp.apps.maas.redhatworkshops.io/v1"

  AzureChatOpenAI:
    environment:
      AZURE_OPENAI_API_KEY: "" # Required
    provider: AzureChatOpenAI
    args:
      azureOpenAIApiDeploymentName: "" # Required
      azureOpenAIApiVersion: "" # Required

  AmazonBedrock:
    environment:
      AWS_ACCESS_KEY_ID: "" # Required
      AWS_SECRET_ACCESS_KEY: "" # Required
      AWS_DEFAULT_REGION: "" # Required
    provider: ChatBedrock
    args:
      model: meta.llama3-70b-instruct-v1:0

  DeepSeek:
    environment:
      DEEPSEEK_API_KEY: "" # Required
    provider: ChatDeepSeek
    args:
      model: deepseek-chat

  GoogleGenAI:
    environment:
      GOOGLE_API_KEY: "" # Required
    provider: ChatGoogleGenerativeAI
    args:
      model: gemini-2.5-pro

  ChatOllama:
    provider: ChatOllama
    args:
      model: your-model-here

active: *active
